// ============================================================================
// OPENCODE CONFIG GENERATOR
// Generates opencode.jsonc based on the gateway model definitions.
// Aligned with the real opencode.ai/config.json schema (ProviderConfig).
// ============================================================================

import { mkdir } from "fs/promises";
import { dirname } from "path";
import type { GatewayConfig } from "../types";

export async function generateOpenCodeConfig(
  cfg: GatewayConfig
): Promise<void> {
  if (!cfg.opencode) return;

  const oc = cfg.opencode;
  const baseURL = `http://127.0.0.1:${cfg.gateway.port}/v1`;
  const defaultModel = cfg.routing.default_model;
  const smallModel = oc.small_model ?? defaultModel;

  // Infer agent → model mappings from routing rules
  const findModelForKeywords = (...keywords: string[]): string => {
    for (const rule of cfg.routing.rules) {
      if (rule.keywords?.some((k) => keywords.includes(k.toLowerCase()))) {
        return rule.model;
      }
    }
    return defaultModel;
  };

  const plannerModel = findModelForKeywords("archivist", "plan", "master-planner");
  const builderModel = findModelForKeywords("build", "deploy", "general", "coder");
  const visionModel =
    cfg.routing.rules.find((r) => r.condition === "has_images")?.model ??
    defaultModel;

  // Build models map block
  const modelsBlock = cfg.models
    .map((m) => `      "${m.id}": { "name": "${m.label}" }`)
    .join(",\n");

  const content = [
    `{`,
    `  "$schema": "https://opencode.ai/config.json",`,
    ``,
    `  // ───────────────────────────────────────────────────────────────────`,
    `  // AUTO-GENERATED by llama-gateway — DO NOT EDIT MANUALLY`,
    `  // Source: gateway.config.yaml`,
    `  // Generated: ${new Date().toISOString()}`,
    `  //`,
    `  // HOW TO USE:`,
    `  //   Option A — Project-level (this project only):`,
    `  //     Copy this file to your project root as opencode.jsonc`,
    `  //`,
    `  //   Option B — Global (all projects):`,
    `  //     Paste the "provider", "model", "small_model", and "agent" blocks`,
    `  //     into: ~/.config/opencode/opencode.jsonc`,
    `  //     Then run: opencode debug config  (to verify the merge worked)`,
    `  // ───────────────────────────────────────────────────────────────────`,
    ``,
    `  // Primary model for heavy tasks (coding, reasoning)`,
    `  "model": "${oc.provider_id}/${defaultModel}",`,
    ``,
    `  // Lightweight model for meta-tasks (title generation, summaries)`,
    `  "small_model": "${oc.provider_id}/${smallModel}",`,
    ``,
    `  "provider": {`,
    `    "${oc.provider_id}": {`,
    `      "name": "${oc.provider_name}",`,
    `      "options": {`,
    `        "baseURL": "${baseURL}",`,
    `        // llama-swap doesn't require auth, but OpenCode needs a non-empty key`,
    `        "apiKey": "llama-gateway"`,
    `      },`,
    `      "models": {`,
    modelsBlock,
    `      }`,
    `    }`,
    `  },`,
    ``,
    `  // Route OpenCode's built-in agents to the right model automatically.`,
    `  // Change these model IDs to match your gateway.config.yaml model ids.`,
    `  "agent": {`,
    `    "plan": {`,
    `      "model": "${oc.provider_id}/${plannerModel}"`,
    `    },`,
    `    "build": {`,
    `      "model": "${oc.provider_id}/${builderModel}"`,
    `    },`,
    `    "general": {`,
    `      "model": "${oc.provider_id}/${defaultModel}"`,
    `    },`,
    `    // Use the small/fast model for lightweight meta-tasks (saves VRAM)`,
    `    "title": {`,
    `      "model": "${oc.provider_id}/${smallModel}"`,
    `    },`,
    `    "summary": {`,
    `      "model": "${oc.provider_id}/${smallModel}"`,
    `    }`,
    `  }`,
    `}`,
    ``,
  ].join("\n");

  const outPath = oc.generated_config_path;
  await mkdir(dirname(outPath), { recursive: true });
  await Bun.write(outPath, content);

  console.log(`[GENERATOR] OpenCode config  → ${outPath}`);
  console.log(
    `\n${"─".repeat(60)}\n` +
      `[OPENCODE] To use with OpenCode, either:\n` +
      `  Copy: ${outPath}\n` +
      `  → To your project root as opencode.jsonc\n` +
      `${"─".repeat(60)}\n`
  );
}
